name: Terraform Plan (Safe Demo)

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      vm_size:
        description: "VM Size"
        required: true
        default: "Standard_B2s"

      os_type:
        description: "Operating System"
        required: true
        type: choice
        options:
          - linux
          - windows

      disk_size:
        description: "Disk Size (GB)"
        required: true
        default: "30"

      location:
        description: "Azure Region"
        required: true
        default: "eastus"

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -refresh=false \
            -var="vm_size=${{ github.event.inputs.vm_size }}" \
            -var="os_type=${{ github.event.inputs.os_type }}" \
            -var="disk_size=${{ github.event.inputs.disk_size }}" \
            -var="location=${{ github.event.inputs.location }}" \
            -var-file="environments/dev.tfvars" \
            -no-color > plan.txt

          cat plan.txt

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: plan.txt